core/src/main/resources/css/mdModuleManager.css

https://jira.jahia.org/browse/QA-12513
- Removed the css style that makes the back button white, as the new header for settings panels in Jahia 8.0 is white

QA-12513: Updated back button color in header

---

core/pom.xml
pom.xml
test/pom.xml

https://jira.jahia.org/browse/BACKLOG-11952

BACKLOG-11952 : Update to 7.5

---

core/pom.xml
pom.xml
test/pom.xml

https://jira.jahia.org/browse/PROJECT-XXX

BACKLOG-11952 : Update version

---

core/src/javascript/registrations/modules/registerRoutes.js
core/yarn.lock

https://jira.jahia.org/browse/BACKLOG-11710
Add requiredPermission into routes

BACKLOG-11710: Add requiredPermission into routes

---

core/package.json

https://jira.jahia.org/browse/BACKLOG-12722
Update registration

BACKLOG-12722 Update package.json

---

core/src/javascript/registrations/modules/registerRoutes.js

https://jira.jahia.org/browse/PROJECT-XXX

BACKLOG-12820: Adapted adminRoute format

---

core/src/javascript/registrations/modules/registerRoutes.js

https://jira.jahia.org/browse/BACKLOG-12935
Simple reordering of the server administration panels

BACKLOG-12935: reordering of the server settings

---

LICENSE.txt
core/pom.xml
core/src/main/java/org/jahia/modules/modulemanager/flow/DuplicateModuleAction.java
core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleFile.java
core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java
core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleVersionState.java
core/src/main/java/org/jahia/modules/modulemanager/forge/Forge.java
core/src/main/java/org/jahia/modules/modulemanager/forge/ForgeService.java
core/src/main/java/org/jahia/modules/modulemanager/forge/Module.java
core/src/main/java/org/jahia/modules/modulemanager/rest/ModuleManagerApplicationConfig.java
core/src/main/java/org/jahia/modules/modulemanager/rest/ModuleManagerExceptionMapper.java
core/src/main/java/org/jahia/modules/modulemanager/rest/ModuleManagerResource.java
core/src/main/java/org/jahia/modules/modulemanager/rest/filters/HeadersResponseFilter.java
core/src/main/java/org/jahia/modules/modulemanager/rest/filters/ModuleManagerAuthenticationRequestFilter.java
core/src/main/resources/META-INF/LICENSE.txt
pom.xml
test/pom.xml
test/src/main/java/org/jahia/test/services/modulemanager/ModuleManagementRestApiTest.java
test/src/main/java/org/jahia/test/services/modulemanager/ModuleManagerDeploymentTest.java
test/src/main/resources/META-INF/LICENSE.txt

Updated copyright year to 2020

BACKLOG-13160 - Updated copyright year

---

core/pom.xml
test/pom.xml

https://jira.jahia.org/browse/BACKLOG-13160

BACKLOG-13160 : Add spring requirement

---

core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java
core/src/main/java/org/jahia/modules/modulemanager/forge/ForgeService.java

https://jira.jahia.org/browse/QA-12758
Ensure jahia required version of the module has the same major number as the current jahai

QA-12758: Compare major version to module required version

---

core/pom.xml
test/pom.xml
test/src/main/java/org/jahia/test/services/modulemanager/ModuleManagerDeploymentTest.java

https://jira.jahia.org/browse/QA-12973
Use dummy1 module version compatible with Jahia 8

QA-12973: Use dummy1 module version compatible with Jahia 8

---

core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/forgeView.jsp
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp

https://jira.jahia.org/browse/QA-13042
Show a work in progress panel while uploading and starting a module as it is done when downloading them. Also avoid showing modal when clicking on Download button from available modules panel

QA-13042: Show a work in progress panel while uploading 

---

core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/forgeView.jsp

https://jira.jahia.org/browse/QA-13028

QA-13028: skip modal opening when downloading module

---

README.md

BACKLOG-15417 - Added a section to the readme about URL encoding

---

test/pom.xml
test/src/main/java/org/jahia/test/services/modulemanager/ModuleManagementRestApiTest.java

https://jira.jahia.org/browse/QABACKLOG-1258
Adapt tests after fixing SonarQube defects

QABACKLOG-1258: Adapt tests after fixing SonarQube defects

---

core/pom.xml
core/src/main/java/org/jahia/modules/modulemanager/rest/ModuleManagerResource.java

https://jira.jahia.org/browse/BACKLOG-15764
Use fileinstall URLTransformer from Felix to transform the resource before calling install
Tested wih npm-plugin-example
`curl -s --user root:root1234 --form bundle=@./npm-plugin-example-v1.0.0.tgz --form start=true http://localhost:8080/modules/api/bundles`                                      
{"bundleInfos":[{"version":"1.0.0","key":"org.jahia.npm/js-npm-plugin-example/1.0.0","symbolicName":"js-npm-plugin-example","groupId":"org.jahia.npm"}],"message":"Operation successful"}⏎

BACKLOG-15764: Transform resource if needed

---

core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/common/moduleLabels.jspf
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/common/moduleVersionActions.jspf
core/src/main/resources/resources/ModuleManager_de.properties
core/src/main/resources/resources/ModuleManager_en.properties
core/src/main/resources/resources/ModuleManager_fr.properties

…
https://jira.jahia.org/browse/BACKLOG-16401

BACKLOG-16401: Allow refreshing if moduleDependenciesWithVersion is empty while dependencies is not

---

core/pom.xml
core/src/main/java/org/jahia/modules/modulemanager/forge/ForgeService.java

https://jira.jahia.org/browse/QA-13892

QA-13892: Fix encoding of urls coming from a store

---

core/pom.xml
core/src/main/java/org/jahia/modules/modulemanager/flow/DuplicateModuleAction.java
core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleFile.java
core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java
core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleVersionState.java
core/src/main/java/org/jahia/modules/modulemanager/forge/Forge.java
core/src/main/java/org/jahia/modules/modulemanager/forge/ForgeService.java
core/src/main/java/org/jahia/modules/modulemanager/forge/Module.java
core/src/main/java/org/jahia/modules/modulemanager/rest/ModuleManagerApplicationConfig.java
core/src/main/java/org/jahia/modules/modulemanager/rest/ModuleManagerExceptionMapper.java
core/src/main/java/org/jahia/modules/modulemanager/rest/ModuleManagerResource.java
core/src/main/java/org/jahia/modules/modulemanager/rest/filters/HeadersResponseFilter.java
core/src/main/java/org/jahia/modules/modulemanager/rest/filters/ModuleManagerAuthenticationRequestFilter.java
pom.xml
test/pom.xml
test/src/main/java/org/jahia/test/services/modulemanager/ModuleManagementRestApiTest.java
test/src/main/java/org/jahia/test/services/modulemanager/ModuleManagerDeploymentTest.java

https://jira.jahia.org/browse/QA-14203

QA-14203 - Update copyright year and license header

---

core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java
core/src/main/java/org/jahia/modules/modulemanager/rest/ModuleManagerResource.java
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.flow/flow.xml
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/flow.xml
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp
core/src/main/resources/resources/ModuleManager_de.properties
core/src/main/resources/resources/ModuleManager_en.properties
core/src/main/resources/resources/ModuleManager_fr.properties
pom.xml

https://jira.jahia.org/browse/BACKLOG-16633
Requires changes from https://github.com/Jahia/jahia-private/tree/BACKLOG-16657

BACKLOG-16633: Add option to bypass checks

---

core/pom.xml
pom.xml
test/pom.xml

https://jira.jahia.org/browse/BACKLOG-16927
* Modify `jahia-parent` dependency to 8.1.2.0
* Update module signatures

BACKLOG-16927: Update module dependency and signature

---

core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.flow/flow.xml
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/flow.xml

https://jira.jahia.org/browse/BACKLOG-16930

BACKLOG-16930: fixed calls

---

core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java
core/src/main/java/org/jahia/modules/modulemanager/message/CustomMessage.java
core/src/main/java/org/jahia/modules/modulemanager/message/MessageService.java
core/src/main/java/org/jahia/modules/modulemanager/message/MessageServiceImpl.java
core/src/main/java/org/jahia/modules/modulemanager/util/ConfigUtil.java
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/view.jsp

https://jira.jahia.org/browse/BACKLOG-17379
Add possibility to use custom messages

BACKLOG-17379 Add possibility to use custom messages

---

core/src/main/java/org/jahia/modules/modulemanager/configuration/OperationConstraintsServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-19914
* Handle deleting configuration through `@Deactivate`
* Merge adding and updating configurations event into one handler function as they do the same thing

BACKLOG-19914: Add handler for delete configuration

---

core/src/main/java/org/jahia/modules/modulemanager/configuration/README.md

https://jira.jahia.org/browse/BACKLOG-20128

BACKLOG-20128: Update constraint configuration format documentation

---

core/webpack.config.js

https://jira.jahia.org/browse/BACKLOG-17249

BACKLOG-17249: Fix module plugin name

---

core/pom.xml
core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/flow.xml
core/src/main/resources/resources/ModuleManager_de.properties
core/src/main/resources/resources/ModuleManager_en.properties
core/src/main/resources/resources/ModuleManager_fr.properties

…
https://jira.jahia.org/browse/BACKLOG-20206
@brigitteradl Could you check the german translation, please?

BACKLOG-20206: Add message (info/warning) about having multiple versions of same module

---

.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml

https://jira.jahia.org/browse/TECH-978
Fix github actions branch

TECH-978: Fix github actions master branch

---

.github/maven.settings.xml
.github/workflows/manual-run.yml
.github/workflows/milestone.yml
.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/on-rollback.yml

https://jira.jahia.org/browse/TECH-1081
Update deprecated steps

TECH-1081 Update deprecated steps

---

core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java
core/src/main/java/org/jahia/modules/modulemanager/flow/OptionalDependency.java
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/common/modulesTableRow.jspf
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/detailedView.jsp
core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/flow.xml
core/src/main/resources/resources/ModuleManager_en.properties
pom.xml

https://jira.jahia.org/browse/TECH-1059
Added messages about optional dependencies (see video on the ticket)

TECH-1059 Add messages about optional dependencies

---

core/src/main/resources/resources/ModuleManager_de.properties
core/src/main/resources/resources/ModuleManager_fr.properties

https://jira.jahia.org/browse/TECH-1059
Added translations in French and German.

Add translations

---

core/pom.xml
core/src/main/import/repository.xml

https://jira.jahia.org/browse/TECH-1091
Update jahia-depends

TECH-1091 Update jahia-depends

---

core/src/main/resources/jnt_serverSettingsManageModules/html/serverSettingsManageModules.settingsBootstrap3GoogleMaterialStyle.flow/forgeView.jsp

https://jira.jahia.org/browse/QA-14632
Remove the "Download" column from the search in the datatable

QA-14632: Exclude Download column from search

---

README.md

https://jira.jahia.org/browse/TECH-1136
Add `target=local` to README definition

TECH-1136: Update readme

---

.github/workflows/on-merge.yml
.github/workflows/on-release.yml
core/package.json
core/pom.xml
core/webpack.config.js
core/yarn.lock

https://jira.jahia.org/browse/TECH-1265
Add cyclonedx-maven-plugin and create/upload SBOMs on merge and release

TECH-1265: Add SBOM creation

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
core/pom.xml
pom.xml
test/pom.xml

https://jira.jahia.org/browse/BACKLOG-21740

BACKLOG-21740: Rollback version upgrade

---

core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java

https://jira.jahia.org/browse/QA-14902
Disable upgrade and install from forge if constraint is present

QA-14902: disable upgrade button

---

core/pom.xml
test/pom.xml

https://jira.jahia.org/browse/TECH-1536

TECH-1536: Add missing dependencies

---

core/src/main/java/org/jahia/modules/modulemanager/rest/filters/ModuleManagerAuthenticationRequestFilter.java
core/src/main/resources/META-INF/configurations/org.jahia.bundles.api.authorization-modulemanager.yml

https://jira.jahia.org/browse/TECH-427
Update the permissions check on the module manager.
The permissions are now compliant to the documentation here https://academy.jahia.com/documentation/jahia/jahia-8/developer/working-with-our-apis/security-service-and-filter#authorization-configuration

TECH-427: improve permission checks

---

core/src/main/java/org/jahia/modules/modulemanager/flow/ModuleManagementFlowHandler.java

https://jira.jahia.org/browse/BACKLOG-23301
Add support in _Module Manager_ to manage installations/updates of javascript modules coming from the _Store_.
Then changes were originally made by @fbourasse in https://support.jahia.com/browse/SUPPORT-317.

BACKLOG-23301: Add support for javascript modules

---

core/src/main/java/org/jahia/modules/modulemanager/forge/ForgeService.java

Forges / Stores were loaded only once, leading to inconsistencies in cluster. 
They are now always loaded from JCR

QA-15170 : always load forges/stores from JCR

---

core/pom.xml
core/src/main/java/org/jahia/modules/modulemanager/configuration/impl/OperationConstraintsServiceImpl.java

https://jira.jahia.org/browse/TECH-1961

feat: expose OperationConstraintsService

---

core/src/main/java/org/jahia/modules/modulemanager/rest/filters/ModuleManagerAuthenticationRequestFilter.java

Backport of https://github.com/Jahia/module-manager/pull/158 onto the 2.8.x branch.
Follows #159 .
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)

fix(security): Disable session authentication on APIs (backport)

---

test/pom.xml
test/src/main/java/org/jahia/test/services/modulemanager/ModuleManagementRestApiTest.java

Backport of https://github.com/Jahia/module-manager/pull/168 onto the maintenance https://github.com/Jahia/module-manager/tree/2_8_x branch.
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)

test(int): Replace session-based auth with basic auth (backport)
